In [11]:
import torch
import torch.nn as nn
import random
import torch.optim as optim
import numpy as np

In [2]:
weights = [1.3, 2.9, 3.7]
w_count = len(weights)

In [43]:
x_list = []
for _ in range(100):
    x_list.append([random.randint(1, 50) for _ in range(w_count)])

x_list[0:10]

[[7, 31, 17],
 [7, 11, 49],
 [7, 40, 7],
 [28, 27, 37],
 [19, 12, 50],
 [5, 41, 14],
 [25, 44, 24],
 [40, 28, 16],
 [2, 47, 19],
 [47, 37, 11]]

In [44]:
inputs = torch.tensor(x_list, dtype=torch.float32, requires_grad=True)
inputs[:10]

tensor([[ 7., 31., 17.],
        [ 7., 11., 49.],
        [ 7., 40.,  7.],
        [28., 27., 37.],
        [19., 12., 50.],
        [ 5., 41., 14.],
        [25., 44., 24.],
        [40., 28., 16.],
        [ 2., 47., 19.],
        [47., 37., 11.]], grad_fn=<SliceBackward0>)

In [45]:
y_list = []
for x in x_list:
    y_list.append(np.dot(x, weights))

y_list[:10]

[161.89999999999998,
 222.3,
 151.0,
 251.6,
 244.5,
 177.2,
 248.9,
 192.39999999999998,
 209.2,
 209.10000000000002]

In [46]:
targets = torch.tensor(y_list, dtype=torch.float32)
targets[:10]

tensor([161.9000, 222.3000, 151.0000, 251.6000, 244.5000, 177.2000, 248.9000,
        192.4000, 209.2000, 209.1000])

In [85]:
# 线性模型
class LNTXModel(nn.Module):
    def __init__(self):
        super(LNTXModel, self).__init__()
        self.linear = nn.Linear(in_features=w_count, out_features=w_count)

    def forward(self, x):
        return self.linear(x)

# 实例化模型
model = LNTXModel()
model

LNTXModel(
  (linear): Linear(in_features=3, out_features=3, bias=True)
)

In [86]:
# 定义损失函数
loss_fn = nn.MSELoss()

# 定义优化器
optimizer = optim.SGD(model.parameters(), lr=0.0005)

In [87]:
# 训练循环，迭代1000次
num_epochs = 1000
for epoch in range(num_epochs):
    for i, x in enumerate(inputs):
        # 前向传播
        predictions = model(x)
        
        # 计算损失
        loss = loss_fn(predictions, targets[i])
        
        # 清空梯度
        optimizer.zero_grad()
        
        # 反向传播
        loss.backward()
        
        # 更新参数
        optimizer.step()
    if (epoch+1) % 100 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

# 训练完成
print('Train done.')

Epoch [100/1000], Loss: 0.0035
Epoch [200/1000], Loss: 0.0019
Epoch [300/1000], Loss: 0.0011
Epoch [400/1000], Loss: 0.0006
Epoch [500/1000], Loss: 0.0003
Epoch [600/1000], Loss: 0.0002
Epoch [700/1000], Loss: 0.0001
Epoch [800/1000], Loss: 0.0001
Epoch [900/1000], Loss: 0.0000
Epoch [1000/1000], Loss: 0.0000
Train done.


In [88]:
print(f'Final weights:{model.linear.weight.data}')
print(f'Final bias:{model.linear.bias.data}')

Final weights:tensor([[1.3000, 2.9000, 3.7000],
        [1.3000, 2.9000, 3.7001],
        [1.3000, 2.9000, 3.6999]])
Final bias:tensor([ 0.0003, -0.0036,  0.0067])


In [72]:
model(torch.tensor([float(1), float(1), float(1)]))

tensor([7.9146, 7.8923, 7.8952], grad_fn=<ViewBackward0>)